### ISSUE TITLE
Unknown attribute 'asmname'

### ISSUE THREAD

**Issue by cSquirrel** [swiftsocket/SwiftSocket#27]
Both yudpsocket.swift and ytcpsocket.swift won't compile with Swift 2.2 (Xcode 7.3 beta) 

Compilation errors refer to Unknown attribute 'asmname', i.e.
`/Users/ciukes/dev/MockJsonServerApp/scm/MockJsonServer/Frameworks/SwiftSocket/SwiftSocket/ysocket/ytcpsocket.swift:32:2: Unknown attribute 'asmname'`

According to Apple dev forum: 
_Swift 2.2 abruptly removed the @asmname attribute in favor of @_silgen_name._
https://forums.developer.apple.com/thread/31497

The same information confirmed elsewhere:
https://github.com/tidwall/SwiftWebSocket/issues/28

**Comment by cSquirrel** [comment]
Both yudpsocket.swift and ytcpsocket.swift won't compile with Swift 2.2 (Xcode 7.3 beta) 

Compilation errors refer to Unknown attribute 'asmname', i.e.
`/Users/ciukes/dev/MockJsonServerApp/scm/MockJsonServer/Frameworks/SwiftSocket/SwiftSocket/ysocket/ytcpsocket.swift:32:2: Unknown attribute 'asmname'`

According to Apple dev forum: 
_Swift 2.2 abruptly removed the @asmname attribute in favor of @_silgen_name._
https://forums.developer.apple.com/thread/31497

The same information confirmed elsewhere:
https://github.com/tidwall/SwiftWebSocket/issues/28

**Comment by aixinlove** [comment]
@cSquirrel thanks
